- static/data/.gitignore
- static/data/parser.py
(And delete the giant `phantomjs` binary.)
> Use BeautifulSoup to parse UkuTabs

- css/convert.css
- css/global.css
- js/convert/convert.js
- js/showAllSongs.js
- js/styles.js
- templates/partials/base.html
- webpack.config.js
> Replace js/styles.js with a CSS entry point and CSS imports

- package.json
- templates/all_songs.html
- templates/aus.html
- templates/convert.html
- templates/import.html
- templates/index.html
- templates/partials/base.html
- webpack.config.js
> Use extract-text-webpack-plugin for CSS

- static/data/ALL_SONGS.json
- static/data/json/bold_orion - leo_kretzner.json
- static/data/text/Bold Orion - Leo Kretzner.txt
e.g. https://www.youtube.com/watch?v=ax3UOQWTZkM
> Add Bold Orion by Leo Kretzner

- static/data/ALL_SONGS.json
- static/data/json/island song - ashley ericsson.json
- static/data/text/island song - ashley ericsson.txt
Hi! Thanks for making this app and sharing your music! Here's "Island Song" by Ashley Ericsson; it's the song that plays at the end of Adventure Time episodes, if you want it.
> Add the cute song that plays at the end of adventure time episodes.

- js/convert/convert.js
- js/index.js
- js/renderChords.js
- js/showAllSongs.js
- package.json
- webpack.config.js
Tested on Heroku this time: https://musicparsed-andersk.herokuapp.com/
> JavaScript bundle size optimization

- static/data/ALL_SONGS.json
- static/data/json/kanade - sukima_switch.json
- static/data/json/lemon - kenshi_yonezu.json
- static/data/text/Kanade - Sukima Switch.txt
- static/data/text/Lemon - Kenshi Yonezu.txt
Add data files for _Kanade_ by Sukima Switch and _Lemon_ by Kenshi Yonezu.
> Add data files for 2 songs

- app.js
- package.json
- templates/all_songs.html
- templates/convert.html
- templates/guides/beginner_ukulele_chords.html
- templates/guides/singing_for_beginners.html
- templates/guides/why_ukulele.html
- templates/index.html
- templates/partials/base.html
- templates/partials/ga.html
- templates/partials/nav.html
- templates/partials/nav_search.html
- templates/partials/social.html
- templates/render_chords.html
- yarn.lock
so Elaine can stop sadfacing at it.
> Remove some Flask compatibility nonsense from app.js

- .eslintrc.js
- package.json
- ts/parser.ts
- ts/tests/testParser.ts
- yarn.lock
DB shenanigans can break stuff. Let's add automated tests to try to catch that.
> Add automated JS tests

- css/global.css
- package.json
- ts/index.ts
- ts/renderChords.ts
- webpack.config.ts
With no proprietary source code to hide, we might as well make debugging easier.
> Enable source maps

- css/global.css
- css/styles.css
close #127 
If your computer is set to use the dark theme, the site will have a black background.
Note: This only works in newest versions of Safari(12.1), and in Firefox nightly (67+).
> * Dark Theme: Add dark theme with a media query

- .circleci/config.yml
Fixes #124. To install, push the button at https://circleci.com/setup-project/gh/elainewlin/MusicParsed.
> Run tests and pre-commit linters in CircleCI

- css/global.css
- css/styles.css
- Add some padding to the bottom of the song view to make it easier to tell when you've reached the end of the song on mobile
- Increase font size on mobile devices
> Mobile enhancements

- README.md
- lib/parser.ts
- models/user.ts
- package.json
- scripts/app.ts
- templates/edit_songs.html
- web/editSongs.ts
- web/songView.ts
- yarn.lock
- Separated functions for adding/editing songs
- On the backend, check to make sure you can only edit/delete songs for your given user
- Enforce unique song IDs when adding songs
- Add client-side validation to prevent empty data
> Add song user validation

- services/password.ts
- services/signup.ts
> #183 fix: adjusts method to store hash correctly

- package.json
- yarn.lock
Update a bunch of dependencies
> Dependabot 2022

- package.json
- yarn.lock
Updating a bunch more Github dependencies
> Dependabot 2023

- .gitignore
- package.json
- scripts/app.ts
- yarn.lock
Reverts elainewlin/MusicParsed#185
Works locally, but not on prod. Boo.
> Revert "DANGEROUS: Bump mongoose from 5.10.0 to 6.13.6"

- package.json
- yarn.lock
Revert this dependabot upgrade: https://github.com/elainewlin/MusicParsed/pull/190
> Revert body parser back to 1.18.3

- package.json
- yarn.lock
Boo popper
Reverts: https://github.com/elainewlin/MusicParsed/pull/199?new_mergebox=true
> Revert adding popper 

- lib/parser.ts
- templates/edit_songs.html
- test/lib/parser.test.ts
- web/editSongs.ts
- More English helper text and error messages.
- Fix long-running parser bug where you can't end a song with chords.
> Improve flow for editing songs
